--- a/Makefile	2014-07-14 11:21:58.000000000 +0400
+++ a/Makefile	2017-04-13 09:52:24.720464468 +0300
@@ -119,7 +119,7 @@
 install:
 	mkdir -p $(DESTDIR)$(libdir)/
 #	cp -af $(APP_LIB_FILES) $(DESTDIR)$(libdir)/
-	cp -af $(APP_LIBXX_FILES) $(DESTDIR)$(libdir)/
+	cp -f -d --preserve=mode $(APP_LIBXX_FILES) $(DESTDIR)$(libdir)/
 	mkdir -p $(DESTDIR)$(includedir)/
 	for d in pjlib pjlib-util pjnath pjmedia pjsip; do \
 		cp -RLf $$d/include/* $(DESTDIR)$(includedir)/; \
