# instead of + linux-firmware (too much space) use this:

IMAGE_INSTALL += "\
 linux-firmware-ar9170 \
 linux-firmware-bcm4329 \
 linux-firmware-bcm4330 \
 linux-firmware-bcm4334 \
 linux-firmware-bcm43340 \
 linux-firmware-bcm43362 \
 linux-firmware-bcm4339 \
 linux-firmware-bcm43430 \
 linux-firmware-bcm4354 \
 linux-firmware-rtl8188 \
 linux-firmware-rtl8821 \
 linux-firmware-sd8686 \
 linux-firmware-sd8688 \
 linux-firmware-sd8787 \
 linux-firmware-sd8797 \
 linux-firmware-sd8801 \
 linux-firmware-sd8887 \
 linux-firmware-sd8897 \
 linux-firmware-ti-connectivity \
 linux-firmware-wl12xx \
 linux-firmware-wl18xx \
"
# linux-firmware-iwlwifi
