
# check if it is NOT in SDK by default
#TOOLCHAIN_TARGET_TASK_append += " epeg-dev"
#TOOLCHAIN_TARGET_TASK_append += " libmatroska-dev"
#TOOLCHAIN_TARGET_TASK_append += " libaio-dev"
#TOOLCHAIN_TARGET_TASK_append += " opencv"


#TOOLCHAIN_TARGET_TASK_append += " tps-capi-dev"
#TOOLCHAIN_TARGET_TASK_append += " tps-sysds-dev"

#TOOLCHAIN_TARGET_TASK_append += " libwinstar-lcd0-dev"

TOOLCHAIN_TARGET_TASK_append += " tps-capi-dev tps-capi-staticdev"
