
# tests and benchmarks
DEPENDS += "dvtests"
DEPENDS += "dvkgpio"
DEPENDS += "twgtest"
DEPENDS += "evtest"

DEPENDS += "tps-gprs"

#DEPENDS += "tps-agent"
#DEPENDS += "tps-ag-stable"
#DEPENDS += "tps-ag-eap"

#DEPENDS += "tps-node-demo"

# i/o Ninja
#DEPENDS += "tdevmon"
#DEPENDS += "tdevmon-kernel"

# lcd
#DEPENDS += "tps-i2c-anum-lcd"

#DEPENDS += "tps-demo-phpliteadmin"

#DEPENDS += "kern-mod-tfwm"

DEPENDS += "tps-capi"