#!/bin/sh

. /etc/init.d/functions

CONFFILE="/home/root/ninja-module.conf"
#NINJA_M_ARGS="maxq_mem=25000 debug_mask=0x00000100"
NINJA_M_ARGS="maxq_mem=120000"

case "$1" in
    start)
    echo "Starting Ninja-module..."
    if [ -f "${CONFFILE}" ]; then
      NINJA_M_ARGS=""
      . ${CONFFILE}
      if [ ! -z "${maxq_free}" ]; then
        NINJA_M_ARGS="${NINJA_M_ARGS}maxq_free=${maxq_free} ";
      fi;
      if [ ! -z "${maxq_mem}" ]; then
        NINJA_M_ARGS="${NINJA_M_ARGS}maxq_mem=${maxq_mem} ";
      fi;
      if [ ! -z "${net_port}" ]; then
        NINJA_M_ARGS="${NINJA_M_ARGS}net_port=${net_port} ";
      fi;
      if [ ! -z "${debug_mask}" ]; then
        NINJA_M_ARGS="${NINJA_M_ARGS}debug_mask=${debug_mask} ";
      fi;
    fi;
#    /sbin/modprobe ninja debug_mask=0x00000100
    /sbin/modprobe ninja ${NINJA_M_ARGS}
    ;;
    stop)
    echo "Stopping Ninja-module..."
    /sbin/rmmod ninja
    ;;
    restart)
    $0 stop
    sleep 1
    $0 start
    ;;
    *)
    echo "Usage: $0 { start | stop | restart }"
    ;;
esac

exit 0
