--- a/Makefile	2020-05-11 19:37:43.650723760 +0300
+++ a/Makefile	2020-05-11 19:38:31.794723301 +0300
@@ -119,7 +119,7 @@
 	@$(OBJDUMP) -d -S $< > $@
 
 $(BIN)/$(TARGET): $(OBJS) $(LD_FILE)
-	@$(LD) $(OBJS) -o $(BIN)/$(TARGET) -Map $(BIN)/$(TARGET).map $(LDFLAGS) $(LDFLAGS_COM)
+	@$(CC) $(OBJS) -o $(BIN)/$(TARGET) -Wl,-Map,$(BIN)/$(TARGET).map $(LDFLAGS) $(LDFLAGS_COM)
 
 $(LD_FILE): $(LD_SRC) $(OBJS)
 	@$(CPP) -P $(CFLAGS) -x c $(LD_SRC) -o $(LD_FILE)
